/*
 * Copyright (c) 2013 Intel Corporation. All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 */

#ifndef ATOMISP_CSI2_REG_H
#define ATOMISP_CSI2_REG_H

/* CSI-2 register ranges */
/* CSI-2 port registers 0..3 (A..D) */
#define CSI2_REG_CSI2_PORT_OFFSET(n)			(0x0400 * (n))
#define CSI2_REG_GPREGS_OFFSET				0x1000

/* CSI-2 port specific sub-ranges */
#define CSI2_REG_CSI2_PORT_CSI_RX_OFFSET		0x0000
#define CSI2_REG_CSI2_PORT_MIPI_BE_OFFSET		0x0100
#define CSI2_REG_CSI2_PORT_PG_OFFSET			0x0200
#define CSI2_REG_CSI2_PORT_IRQ_CONTROLLER_OFFSET	0x0300

#define __CSI2_PORT_REG(port, subrange, reg)		\
	(CSI2_REG_CSI2_PORT_OFFSET(port)		\
	 + CSI2_REG_CSI2_PORT_##subrange##_OFFSET	\
	 + CSI2_REG_##subrange##_##reg)

#define CSI2_REG_CSI_RX_ENABLE				0x00
#define CSI2_CSI_RX_ENABLE_ENABLE			0x01
#define CSI2_REG_CSI_RX_NOF_ENABLED_LANES		0x04
#define CSI2_REG_CSI_RX_HBP_TESTMODE_ENABLE		0x08
#define CSI2_REG_CSI_RX_ERROR_HANDLING			0x0c
#define CSI2_REG_CSI_RX_SP_IF_CONFIG			0x10
#define CSI2_REG_CSI_RX_LP_IF_CONFIG			0x14
#define CSI2_REG_CSI_RX_STATUS				0x18
#define CSI2_CSI_RX_STATUS_BUSY				0x01
#define CSI2_REG_CSI_RX_STATUS_DLANE_HS			0x1c
#define CSI2_REG_CSI_RX_STATUS_DLANE_LP			0x20
#define CSI2_REG_CSI_RX_DLY_CNT_TERMEN_CLANE		0x24
#define CSI2_REG_CSI_RX_DLY_CNT_SETTLE_CLANE		0x28
/* 0..3 */
#define CSI2_REG_CSI_RX_DLY_CNT_TERMEN_DLANE(n)		(0x2c + (n) * 8)
#define CSI2_REG_CSI_RX_DLY_CNT_SETTLE_DLANE(n)		(0x30 + (n) * 8)

#define CSI2_REG_MIPI_BE_ENABLE				0x00
#define CSI2_MIPI_BE_ENABLE_ENABLE			0x01
#define CSI2_REG_MIPI_BE_STATUS				0x04
#define CSI2_MIPI_BE_STATUS_BUSY			0x01
#define CSI2_REG_MIPI_BE_COMP_FORMAT_VC(n)		(0x08 + (n) * 4)
#define CSI2_MIPI_BE_COMP_FORMAT_VC_COMPRESS_SHIFT(n)	((n) * 4)
#define CSI2_MIPI_BE_COMP_FORMAT_VC_UNCOMPRESSED	0x00
#define CSI2_MIPI_BE_COMP_FORMAT_VC_DPCM_10_6_10	0x01
#define CSI2_MIPI_BE_COMP_FORMAT_VC_DPCM_10_7_10	0x02
#define CSI2_MIPI_BE_COMP_FORMAT_VC_DPCM_10_8_10	0x03
#define CSI2_MIPI_BE_COMP_FORMAT_VC_DPCM_12_6_12	0x04
#define CSI2_MIPI_BE_COMP_FORMAT_VC_DPCM_12_7_12	0x05
#define CSI2_MIPI_BE_COMP_FORMAT_VC_DPCM_12_8_12	0x06
#define CSI2_MIPI_BE_COMP_FORMAT_VC_PREDICTOR_SHIFT(n)	(3 + (n) * 4)
#define CSI2_MIPI_BE_COMP_FORMAT_VC_PREDICTOR_COMPONENT_AGNOSTIC	0x00
#define CSI2_MIPI_BE_COMP_FORMAT_VC_PREDICTOR_PER_COMPONENT	0x01
#define CSI2_REG_MIPI_BE_RAW16_CONFIG			0x18
#define CSI2_REG_MIPI_BE_RAW18_CONFIG			0x1c
#define CSI2_REG_MIPI_BE_FORCE_RAW8			0x20
#define CSI2_MIPI_BE_FORCE_RAW8_ENABLE			0x01
#define CSI2_MIPI_BE_FORCE_RAW8_LONG_DECODE_TYPE	0x02
#define CSI2_MIPI_BE_FORCE_RAW8_DECODE_TYPE_SHIFT	0x02
#define CSI2_MIPI_BE_FORCE_RAW8_DECODE_TYPE_MASK	0xfc
#define CSI2_REG_MIPI_BE_IRQ_STATUS			0x24
#define CSI2_REG_MIPI_BE_IRQ_CLEAR			0x28
#define CSI2_REG_MIPI_BE_CUST_EN			0x2c
#define CSI2_REG_MIPI_BE_CUST_DATA_STATE		0x30
/* s [0,2]; p [0,3] */
#define CSI2_REG_MIPI_BE_CUST_PIX_EXT_SP(s, p)		(0x34 + ((s) * 4 + (p)) * 4)
#define CSI2_REG_MIPI_BE_CUST_PIX_VALID_EOP		0x64
#define CSI2_REG_MIPI_BE_GLOBAL_LUT_DISREGARD		0x68
#define CSI2_MIPI_BE_GLOBAL_LUT_DISREGARD_DISCARD	0x01
#define CSI2_REG_MIPI_BE_PKT_STALL_STATUS		0x6c
#define CSI2_MIPI_BE_PKT_STALL_STATUS_FORMAT_MASK	0x003f
#define CSI2_MIPI_BE_PKT_STALL_STATUS_VC_MASK		0x0003
#define CSI2_MIPI_BE_PKT_STALL_STATUS_VC_SHIFT		6
#define CSI2_MIPI_BE_PKT_STALL_STATUS_STALLED		0x0100
#define CSI2_REG_MIPI_BE_PARSE_GSPTHROUGH_LP_LUT_REG_IDX	0x70
#define CSI2_MIPI_BE_PARSE_GSPTHROUGH_LP_LUT_REG_IDX_LP_LUT_ENABLE	0x01
#define CSI2_MIPI_BE_PARSE_GSPTHROUGH_LP_LUT_REG_IDX_VSYNC_INSERT	0x02
/* 0..3 */
#define CSI2_REG_MIPI_BE_SP_LUT_ENTRY_VC(n)		(0x74 + (n) * 4)
#define CSI2_MIPI_BE_SP_LUT_ENTRY_VC_PASS_MASK		0x01
#define CSI2_MIPI_BE_SP_LUT_ENTRY_VC_PASS_DISCARD	0x01
#define CSI2_MIPI_BE_SP_LUT_ENTRY_VC_SID_MASK		0x0f
#define CSI2_MIPI_BE_SP_LUT_ENTRY_VC_SID_SHIFT		0x01
/* 0..15 */
#define CSI2_REG_MIPI_BE_LP_LUT_ENTRY(n)		(0x84 + (n) * 4)
#define CSI2_MIPI_BE_LP_LUT_ENTRY_PASS_MASK		0x01
#define CSI2_MIPI_BE_LP_LUT_ENTRY_PASS_DISCARD		0x01
#define CSI2_MIPI_BE_LP_LUT_ENTRY_SID_MASK		0x0f
#define CSI2_MIPI_BE_LP_LUT_ENTRY_SID_SHIFT		0x01
#define CSI2_MIPI_BE_LP_LUT_ENTRY_VC_MASK		0x03
#define CSI2_MIPI_BE_LP_LUT_ENTRY_VC_SHIFT		0x05
#define CSI2_MIPI_BE_LP_LUT_ENTRY_CSI2_FORMAT_MASK	0x3f
#define CSI2_MIPI_BE_LP_LUT_ENTRY_CSI2_FORMAT_SHIFT	0x07

#define CSI2_REG_PG_COM_ENABLE				0x00
#define CSI2_REG_PG_PRBS_RSTVAL0			0x04
#define CSI2_REG_PG_PRBS_RSTVAL1			0x08
#define CSI2_REG_PG_SYNG_SID				0x0c
#define CSI2_REG_PG_SYNG_FREE_RUN			0x10
#define CSI2_REG_PG_SYNG_PAUSE				0x14
#define CSI2_REG_PG_SYNG_NOF_FRAME			0x18
#define CSI2_REG_PG_SYNG_NOF_PIXEL			0x1c
#define CSI2_REG_PG_SYNG_NOF_LINE			0x20
#define CSI2_REG_PG_SYNG_HBLANK_CYC			0x24
#define CSI2_REG_PG_SYNG_VBLANK_CYC			0x28
#define CSI2_REG_PG_SYNG_STAT_HCNT			0x2c
#define CSI2_REG_PG_SYNG_STAT_VCNT			0x30
#define CSI2_REG_PG_SYNG_STAT_FCNT			0x34
#define CSI2_REG_PG_SYNG_STAT_DONE			0x38
#define CSI2_REG_PG_TPG_MODE				0x3c
#define CSI2_REG_PG_TPG_HCNT_MASK			0x40
#define CSI2_REG_PG_TPG_VCNT_MASK			0x44
#define CSI2_REG_PG_TPG_XYCNT_MASK			0x48
#define CSI2_REG_PG_TPG_HCNT_DELTA			0x4c
#define CSI2_REG_PG_TPG_VCNT_DELTA			0x50
#define CSI2_REG_PG_TPG_R1				0x54
#define CSI2_REG_PG_TPG_G1				0x58
#define CSI2_REG_PG_TPG_B1				0x5c
#define CSI2_REG_PG_TPG_R2				0x60
#define CSI2_REG_PG_TPG_G2				0x64
#define CSI2_REG_PG_TPG_B2				0x68

/* 0 == falling; 1 == rising */
#define CSI2_REG_IRQ_EDGE				0x00
#define CSI2_REG_IRQ_MASK				0x04
#define CSI2_REG_IRQ_STATUS				0x08
#define CSI2_REG_IRQ_CLEAR				0x0c
#define CSI2_REG_IRQ_ENABLE				0x10
/* 0 == edge; 1 == level */
#define CSI2_REG_IRQ_LEVEL_NOT_PULSE			0x14

/* Register bits for all the above registers */
#define CSI2_IRQ_CSI_RX_SINGLE_PKT_HEADER_ERROR		(1 << 0)
#define CSI2_IRQ_CSI_RX_MULTIPLE_PKT_HEADER_ERRORS	(1 << 1)
#define CSI2_IRQ_CSI_RX_CRC_ERROR			(1 << 2)
#define CSI2_IRQ_CSI_RX_FIFO_OVERFLOW			(1 << 3)
#define CSI2_IRQ_CSI_RX_RESERVED_SHORT_PKT		(1 << 4)
#define CSI2_IRQ_CSI_RX_RESERVED_LONG_PKT		(1 << 5)
#define CSI2_IRQ_CSI_RX_INCOMPLETE_LONG_PKT		(1 << 6)
#define CSI2_IRQ_CSI_RX_FRAME_SYNC_ERROR		(1 << 7)
#define CSI2_IRQ_CSI_RX_LINE_SYNC_ERROR			(1 << 8)
#define CSI2_IRQ_CSI_RX_DPHY_START_OF_TRANSM_ERROR	(1 << 9)
#define CSI2_IRQ_CSI_RX_DPHY_SYNC_ERROR			(1 << 10)
#define CSI2_IRQ_CSI_RX_ESCAPE_ERROR			(1 << 11)
#define CSI2_IRQ_CSI_RX_ESCAPE_TRIGGER_EVENT		(1 << 12)
#define CSI2_IRQ_CSI_RX_ESCAPE_ULTRA_LOW_POWER_ENTER	(1 << 13)
#define CSI2_IRQ_CSI_RX_ESCAPE_ULTRA_LOW_POWER_EXIT	(1 << 14)
#define CSI2_IRQ_CSI_RX_INTER_FRAME_SHORT_PKT_DISCARDED	(1 << 15)
#define CSI2_IRQ_CSI_RX_INTER_FRAME_LONG_PKT_DISCARDED	(1 << 16)
#define CSI2_IRQ_MIPI_BE_NON_MATCHING_LONG_PKT_STALLED	(1 << 17)

#define CSI2_REG_GPREG_SRST				0x00
/* 0..3 (A..D) */
#define CSI2_GPREG_SRST_CSI_RX(n)			(1 << ((n) * 4))
#define CSI2_GPREG_SRST_MIPI_BACKEND(n)			(1 << ((n) * 4 + 1))
#define CSI2_GPREG_SRST_PG(n)				(1 << ((n) * 4 + 2))
#define CSI2_GPREG_SRST_STREAM_MUX(n)			(1 << ((n) * 4 + 3))
#define CSI2_REG_GPREG_SLV_REG_SRST			0x04
/* 0..3 (A..D) */
#define CSI2_GPREG_SLV_REG_SRST_CSI_RX(n)		(1 << ((n) * 3))
#define CSI2_GPREG_SLV_REG_SRST_MIPI_BACKEND(n)		(1 << ((n) * 3 + 1))
#define CSI2_GPREG_SLV_REG_SRST_PG(n)			(1 << ((n) * 3 + 2))
#define CSI2_REG_GPREG_FB_HPLL_FREQ			0x08
#define CSI2_REG_GPREG_ISCLK_RATIO			0x0c

#endif /* ATOMISP_CSI2_REG_H */
