atomisp-mod-objs			+= atomisp.o atomisp-bus.o atomisp-dma.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-mod.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-csi2.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-mmu.o
