atomisp-mod-objs			+= atomisp.o atomisp-bus.o atomisp-dma.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-mod.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-mmu.o
atomisp-isys-mod-objs			+= atomisp-isys.o atomisp-csi2.o \
					   atomisp-isys-video.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-isys-mod.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-psys.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-buttress.o
