atomisp-mod-objs			+= atomisp.o atomisp-bus.o atomisp-dma.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-mod.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-csi2.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-mmu.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-isys.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-psys.o
obj-$(CONFIG_VIDEO_ATOMISP_NG)		+= atomisp-buttress.o
