css2600-mod-objs			+= css2600.o css2600-bus.o css2600-dma.o
obj-$(CONFIG_VIDEO_CSS2600)		+= css2600-mod.o
obj-$(CONFIG_VIDEO_CSS2600)		+= css2600-mmu.o
css2600-isys-mod-objs			+= css2600-isys.o css2600-isys-csi2.o \
					   css2600-isys-csi2-2401.o \
					   css2600-isys-video.o \
					   css2600-isys-queue.o \
					   css2600-isys-subdev.o \
					   css2600-isys-tpg.o
obj-$(CONFIG_VIDEO_CSS2600)		+= css2600-isys-mod.o
obj-$(CONFIG_VIDEO_CSS2600)		+= css2600-psys.o
obj-$(CONFIG_VIDEO_CSS2600)		+= css2600-buttress.o

include $(srctree)/$(src)/Makefile.lib2401
